vndk: Add missing definition of COSITED_VERTICAL and COSITED_BOTH
COSITED_VERTICAL and COSITED_BOTH are not defined in
vndk Graphics headers of v34. Let's define it to avoid
build issue.

This changes are based on changes of riscv64.

Logs:

error: no member named 'COSITED_VERTICAL'
error: no member named 'COSITED_BOTH'

Signed-off-by: Kha Tran <tranchikha1106@gmail.com>